fun/fun/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve as serve_static

urlpatterns = [

    path('', include('funhome.urls')),

    path('admin/', admin.site.urls),

    path('funfile/', include('funfile.urls')),

    path('eduhub/', include('eduhub.urls')),

    path('funblog/', include('funblog.urls')),

    path('notification/', include('fnotification.urls')),

    path('accounts/', include('allauth.urls')),

    path('funuser/', include('funuser.urls')),

    path('ckeditor/', include('fun._ckeditor_uploader_url')),

    # path('django_bfm/', include('django_bfm.urls')),

    path('static/<path:path>', serve_static, \
         {'document_root': settings.SERVE_STATIC_ROOT},),
    path('media/<path:path>', serve_static, \
         {'document_root': settings.MEDIA_ROOT},),

]  # + static( settings.STATIC_URL, document_root =  settings.STATIC_ROOT  )

if not settings.ALLOWED_REGISTRATION:
    urlpatterns = [path('accounts/signup/', include('funhome.urls'))] +\
        urlpatterns

fun/funuser/urls.py
from django.urls import path

from . import views
from .apps import FunuserConfig

app_name = FunuserConfig.name

urlpatterns = [
    path('funuser_update/', views.FunuserUpdateView.as_view(),
         name='funuser_update'),
    path('funuser_detail/<int:user_id>',
         views.FunuserDetailView.as_view(), name='funuser_detail'),
]

fun/funuser/models.py
import os
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField

# Create your models here.


funuser_mame = 'funuser'


def upload_to(instance, filename):
    return '{0}/{1}'.format(instance.username, filename)


class Funuser(AbstractUser):

    avatar = models.ImageField(
        upload_to=upload_to, blank=True, verbose_name=_('Avatar'), )

    birth_date = models.DateField(
        blank=True, null=True, verbose_name=_('Brith date'))
    is_birth_date_outward = models.BooleanField(
        default=False, verbose_name=_('Is outward') + ' ?')

    address = models.CharField(
        blank=True, max_length=64, verbose_name=_('Address'))
    is_address_outward = models.BooleanField(
        default=False, verbose_name=_('Is outward') + ' ?')

    hometown = models.CharField(
        blank=True, max_length=64, verbose_name=_('Hometown'))
    is_hometown_outward = models.BooleanField(
        default=False, verbose_name=_('Is outward') + ' ?')

    college = models.CharField(
        blank=True, max_length=64, verbose_name=_('College'))

    is_college_outward = models.BooleanField(
        default=False, verbose_name=_('Is outward') + ' ?')

    occupation = models.CharField(
        blank=True, max_length=64, verbose_name=_('Occupation'))
    is_occupation_outward = models.BooleanField(
        default=False, verbose_name=_('Is outward') + ' ?')

    hobby = models.CharField(blank=True, max_length=64,
                             verbose_name=_('Hobby'))
    is_hobby_outward = models.BooleanField(
        default=False, verbose_name=_('Is outward') + ' ?')

    motto = models.CharField(blank=True, max_length=64,
                             verbose_name=_('Motto'))

    is_motto_outward = models.BooleanField(
        default=False, verbose_name=_('Is outward') + ' ?')

fun/funuser/views.py
# Create your views here.

import math
import os

import magic
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core import paginator
from django.core.exceptions import ValidationError
from django.core.files import File
from django.http import Http404
from django.shortcuts import (Http404, HttpResponseRedirect, redirect, render,
                              reverse)
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from .apps import FunuserConfig
from .modelforms import FunuserModelForm
from .models import Funuser, funuser_mame

funuser_create_template = f'funuser/funuser_create.html'
funuser_detail_template = f'funuser/funuser_detail.html'
funuser_delete_template = f'funuser/funuser_delete.html'
funuser_update_template = f'funuser/funuser_update.html'
funuser_list_template = f'funuser/funuser_list.html'


class FunuserUpdateView(LoginRequiredMixin, UpdateView):

    model = Funuser
    form_class = FunuserModelForm
    template_name = funuser_update_template
    success_url = reverse_lazy('funuser:funuser_update')

    def get_object(self, queryset=None):
        return self.request.user

    def post(self, request, *args, **kwargs):
        print(request)
        if not Funuser.objects.filter(id=request.user.id).exists():
            return Http404()
        return super().post(request, *args, **kwargs)


class FunuserDetailView(LoginRequiredMixin, DetailView):
    model = Funuser
    template_name = funuser_detail_template
    pk_url_kwarg = 'user_id'

fun/funuser/templates/funuser/_funuser_url.html
{% load static %}

{% load crispy_forms_tags %}

{% load i18n %}
{% load l10n %}

<ul class="nav nav-pills nav-item text-right user-info-nav-pills">
    <li class="nav-item">
        <a class="btn btn-sm" href="{% url 'funuser:funuser_update' %}">
            {% trans 'Information' %}</a>
    </li>
    <li class="nav-item ml-2">
        <a class="btn btn-sm" href="/accounts/password/reset/">
            {% trans 'Reset password' %}</a>
    </li>
    <li class="nav-item ml-2">
        <a class="btn btn-sm" href="/funblog">
            {% trans 'My Blog' %}&#10138;</a>
    </li>
</ul>
<hr/>

fun/funuser/templates/funuser/funuser_detail.html
{% extends 'funhome/_base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load i18n %}
{% load l10n %}

{% block title %}User Information{% endblock title %}

{% block content %}  
    
    {% if not is_funuser_created %}
        <h5>
            {% blocktrans %}
                {{ funuser.user }} left nothing here
            {% endblocktrans %}
        </h5>
    {% else %}

        <div class="row">
            <div class="col col-auto text-center" >
                <img  src="
            {% if funuser.avatar.name %}
                /media/{{ funuser.avatar.name  }}
            {% endif %}" 
                    alt="avatar" class="rounded-circle "   
                    style="width: 150px;height:150px;object-fit: cover"/>

                <div class="form-group mt-2 text-center">
                    <h2>{{ funuser.full_name }}</h2> 
                </div>
            </div>

            <div class="col col-auto">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col"></th> 
                        </tr>
                    </thead>
                    <tbody>
                        
                        {% if funuser.is_birth_date_outward %}
                            <tr>
                                <th scope="row"> {% trans 'Birth date' %}</th>
                                <td>{{ funuser.birth_date }}</td>
                            </tr> 
                        {% endif %}

                        {% if funuser.is_address_outward %}
                            <tr>
                                <th scope="row"> {% trans 'Address' %}</th>
                                <td>{{ funuser.address }}</td>
                            </tr> 
                        {% endif %}

                        {% if funuser.is_hometown_outward %}
                            <tr>
                                <th scope="row"> {% trans 'Hometown' %}</th>
                                <td>{{ funuser.hometown }}</td>
                            </tr> 
                        {% endif %}

                        {% if funuser.is_college_outward %}
                            <tr>
                                <th scope="row"> {% trans 'College' %}</th>
                                <td>{{ funuser.college }}</td>
                            </tr> 
                        {% endif %}

                        {% if funuser.is_occupation_outward %}
                            <tr>
                                <th scope="row"> {% trans 'Occupation' %}</th>
                                <td>{{ funuser.occupation }}</td>
                            </tr> 
                        {% endif %}

                        {% if funuser.is_motto_outward %}
                            <tr>
                                <th scope="row"> {% trans 'Motto' %}</th>
                                <td>{{ funuser.motto }}</td>
                            </tr> 
                        {% endif %}

                    </tbody>
                </table>
 
           
                            
            </div>
        </div>
            
    {% endif %}

{% endblock %}
 

fun/funuser/templates/funuser/funuser_update.html
{% extends 'funhome/_base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load i18n %}
{% load l10n %}

{% block title %}Home{% endblock title %}

{% block content %} 
    {% include 'funuser/_funuser_url.html' %}
    
    <form method="post"  enctype="multipart/form-data" class="mt-2" >
            
        {% csrf_token %}

        {{ form.non_field_errors }} 
        <div class="row">
            <div class="col col-auto text-center" >
                <img  click-to='#id_avatar' id='id_avatar_show' 
                    src="
        {% if form.instance.avatar.name %}
            /media/{{ form.instance.avatar.name }}
        {% endif %}" alt="avatar" class="rounded-circle "   
                    style="width: 150px;height:150px;object-fit: cover"/>

                <div hidden>
                    {{ form.avatar }} 
                </div>
                
                <div class="input-group">
                    {{ form.first_name.errors }} 
                    {{ form.first_name }}
                    {{ form.last_name.errors }} 
                    {{ form.last_name }}
                </div>  

            </div>

            <div class="col col-auto">

                <div class="form-group">
                        {{ form.birth_date.errors }}
                    <label  >
                        {% trans 'Birth date' %}
                        <span class="custom-control custom-switch"  
                            style="display: inline;">
                            {{ form.is_birth_date_outward }}
                            <span class="custom-control-label" 
                                for="id_is_birth_date_outward">
                                {% trans 'is outward' %}?
                            </span>
                        </s>
                    </label>
                    <input type="date" name="birth_date" 
                        value='{{ form.birth_date.value|date:"Y-m-d" }}' 
                        class="form-control" 
                        id="{{ form.birth_date.id_for_label }}"/>
                </div>
                
        
                <div class="form-group">
                    {{ form.address.errors }}
                    <label >
                        {% trans 'Address' %}
        
                        <div class="custom-control custom-switch"
                            style="display: inline;">
                            {{ form.is_address_outward }}
                            
                            <label class="custom-control-label" 
                                for="id_is_address_outward">
                                {% trans 'is outward' %}?
                            </label>

                        </div>
                    </label>
                    {{ form.address }}
                </div>
            
                <div class="form-group">
                    {{ form.hometown.errors }}
                    <label >
                        {% trans 'Hometown' %}
                        <div class="custom-control custom-switch " 
                            style="display: inline;">
                            {{ form.is_hometown_outward }}
                            <label class="custom-control-label" 
                                for="id_is_hometown_outward">
                                {% trans 'is outward' %}?
                            </label>

                        </div>
                    </label>
                    {{ form.hometown }}
                </div>
        
                <div class="form-group">
                    {{ form.college.errors }}
                    <label >
                        {% trans 'College' %}
                        <div class="custom-control custom-switch" 
                            style="display: inline;">
                            {{ form.is_college_outward }}
                            <label class="custom-control-label" 
                                for="id_is_college_outward">
                                {% trans 'is outward' %}?
                            </label>
                        </div>
                    </label>
                    {{ form.college }}
                </div>
        
                <div class="form-group">
                    {{ form.occupation.errors }}
                    <label >
                        {% trans 'Occupation' %}
                        <div class="custom-control custom-switch" 
                            style="display: inline;">
                            {{ form.is_occupation_outward }}
                            <label class="custom-control-label" 
                                for="id_is_occupation_outward">
                                {% trans 'is outward' %}?
                            </label>
                        </div>
                    </label>
                    {{ form.occupation }}
                </div>
        
                <div class="form-group">
                    {{ form.motto.errors }}
                    <label >
                        {% trans 'Motto' %}
                        <div class="custom-control custom-switch" 
                            style="display: inline;">
                            {{ form.is_motto_outward }}
                            <label class="custom-control-label" 
                                for="id_is_motto_outward">
                                {% trans 'is outward' %}?
                            </label>
                        </div>
                    </label>
                    {{ form.motto }}
                </div>
                            
            </div>
        </div>
                               
        <div class="col col-12 text-right" >                             
            <input class="btn btn-outline-info " type="submit" 
                value="{% trans 'Upload' %}" />
        </div>
    </form>    


{% endblock content %}

{% block optionaljs %}
    <script src="{% static 'funuser/funuser.js' %}"></script>
{% endblock optionaljs %}