fun/fun/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve as serve_static

urlpatterns = [

    path('', include('funhome.urls')),

    path('admin/', admin.site.urls),

    path('funfile/', include('funfile.urls')),

    path('eduhub/', include('eduhub.urls')),

    path('funblog/', include('funblog.urls')),

    path('notification/', include('fnotification.urls')),

    path('accounts/', include('allauth.urls')),

    path('funuser/', include('funuser.urls')),

    path('ckeditor/', include('fun._ckeditor_uploader_url')),

    # path('django_bfm/', include('django_bfm.urls')),

    path('static/<path:path>', serve_static, \
         {'document_root': settings.SERVE_STATIC_ROOT},),
    path('media/<path:path>', serve_static, \
         {'document_root': settings.MEDIA_ROOT},),

]  # + static( settings.STATIC_URL, document_root =  settings.STATIC_ROOT  )

if not settings.ALLOWED_REGISTRATION:
    urlpatterns = [path('accounts/signup/', include('funhome.urls'))] +\
        urlpatterns

fun/funhome/urls.py
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from . import views

urlpatterns = [

    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    path('homesticker_detail/<uuid:pk>',
         views.HomestickerDetailView.as_view(), name='homesticker_detail'),
    path('homesticker_list', views.HomestickerListView.as_view(),
         name='homesticker_list'),

    path('funhomesticker_detail/<uuid:pk>',
         views.FunhomestickerDetailView.as_view(),
         name='funhomesticker_detail'),
    path('funhomesticker_list', views.FunhomestickerListView.as_view(),
         name='funhomesticker_list'),

    path('appreciation_detail/<uuid:pk>',
         views.AppreciationDetailView.as_view(),
         name='appreciation_detail'),

    path('data_privacy', views.data_privacy, name='data_privacy'),
    path('legal_information', views.legal_information,
         name='legal_information'),

    path('favicon.ico', views.get_favicon_ico, name='favicon.ico'),

    path('#', views.HomeView.as_view(), name='##'),
    path('', views.HomeView.as_view(), name='#'),
]

fun/eduhub/models.py
import hashlib
import os
import uuid

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import (RichTextUploadingField,
                                      RichTextUploadingFormField)
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from django.core.exceptions import ValidationError
from django.core.validators import *
from django.db import models
from django.utils.translation import gettext_lazy as _
from funfile.storage import upload_to
from funuser.models import Funuser

# Create your models here.

label_name = 'label'
funtest_name = 'funtest'
content_name = 'content'
funcontent_name = 'funcontent'
eduhubhomesticker_name = 'eduhubhomesticker'
classification_name = 'classification'


#  _____                            _             _
# |  ___|   _ _ __   ___ ___  _ __ | |_ ___ _ __ | |_
# | |_ | | | | '_ \ / __/ _ \| '_ \| __/ _ \ '_ \| __|
# |  _|| |_| | | | | (_| (_) | | | | ||  __/ | | | |_
# |_|   \__,_|_| |_|\___\___/|_| |_|\__\___|_| |_|\__|

class Classification(models.Model):
    class Meta:
        verbose_name = _('Classification')
        verbose_name_plural = _('Classifications')

    def __str__(self):
        return (
            '' if self.parent is None
            else str(self.parent) + '/'
        ) + _(self.name)

    def clean(self):
        if '/' in self.name:
            raise ValidationError({
                'name': _("name includes '/' is not allowed")})

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True)

    parent = models.ForeignKey(
        to='self', null=True, blank=True, on_delete=models.CASCADE,
        verbose_name=_('Parent classification'))

    name = models.CharField(
        max_length=64, blank=False,
        verbose_name=_("Classification name('/' cannot be included)"))

    comment = models.CharField(
        null=True, blank=True,
        max_length=64, verbose_name=_('Classification comment'))


def label_upload_to(instance, filename):
    return '{0}/{1}'.format(instance.author.username, filename)


class Label(models.Model):

    class Meta:
        verbose_name = _('Eduhub label')
        verbose_name_plural = _('Eduhub  labels')

    def __str__(self):
        return self.name

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(
        max_length=64, blank=False,
        verbose_name=_('Label name'))
    comment = models.CharField(
        max_length=64, verbose_name=_('Label comment'))
    cover = models.ImageField(
        upload_to=label_upload_to, blank=True, verbose_name=_('Label cover'))
    creating_date = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Label creating date'))
    author = models.ForeignKey(
        to=Funuser, on_delete=models.CASCADE, verbose_name=_('Label author'))
    is_legal = models.BooleanField(
        default=True, verbose_name=_('Is label legal') + " ?")


class Funcontent(models.Model):

    class Meta:
        verbose_name = _('Eduhub content (NEW)')
        verbose_name_plural = _('Eduhub contents (NEW)')

    def __str__(self):
        return self.title

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        unique=True)

    label = models.ForeignKey(
        to=Label, on_delete=models.SET_NULL, null=True,
        verbose_name=_('Content label'))

    classification = models.ForeignKey(
        to=Classification, blank=True, null=True, on_delete=models.SET_NULL,
        verbose_name=_('Content classification'))

    title = models.CharField(max_length=64, blank=False,
                             verbose_name=_('Content title'))

    content = RichTextUploadingField(max_length=2048,
                                     verbose_name=_('Content'))

    uploading_date = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Content uploading date'))
    comment = models.TextField(
        max_length=64, verbose_name=_('Content comment'))
    is_legal = models.BooleanField(
        default=True, verbose_name=_('Is content legal'))


def eduhubhomesticker_upload_to(instance, filename):
    return '{0}/{1}'.format(instance.promulgator.username, filename)


class Eduhubhomesticker(models.Model):
    class Meta:
        verbose_name = _('Eduhub homepage sticker')
        verbose_name_plural = _('Eduhub homepage stickers')

    def __str__(self):
        return self.title

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False,)
    title = models.CharField(
        max_length=32,
        verbose_name=_('Eduhub homepage sticker title'))

    subtitle = models.TextField(
        max_length=64,
        verbose_name=_('Eduhub homepage sticker subtitle'))

    cover = models.ImageField(
        upload_to=eduhubhomesticker_upload_to,
        verbose_name=_('Eduhub homepage sicker cover'))

    promulgator = models.ForeignKey(
        to=Funuser, on_delete=models.CASCADE,
        verbose_name=_('Eduhub homepage sticker promulgator'))

    description = RichTextUploadingField()

    content = RichTextUploadingField()

    promulgating_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Eduhub homepage sticker promulgating date'))

    comment = models.TextField(max_length=128, verbose_name=_(
        'Eduhub homepage sticker comment'))

    is_hidden = models.BooleanField(
        default=False, verbose_name=_('Hidden') + " ?")


class Funtest(models.Model):

    class Meta:
        verbose_name = _('Eduhub Test')
        verbose_name_plural = _('Eduhub Tests')

    def __str__(self):
        return self.name

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4,
        editable=False, unique=True)

    test_title = models.CharField(
        max_length=64, blank=True, null=True,
        verbose_name=_('Test commit'))

    test_owner = models.ForeignKey(
        to=Funuser, on_delete=models.CASCADE,
        verbose_name=_('Test owner'))

    test_text = models.TextField(
        max_length=12288,
        verbose_name=_('Template text'))

    submitting_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Test submitting date'))

    last_modifying_date = models.DateTimeField(
        blank=True, null=True,
        verbose_name=_('Last modifying date'))

    test_commit = models.CharField(
        max_length=64, blank=True, null=True,
        verbose_name=_('Test commit'))


#
#     _                          _     _
#    / \   _ __  _ __  _ __ __ _(_)___(_)_ __   __ _
#   / _ \ | '_ \| '_ \| '__/ _` | / __| | '_ \ / _` |
#  / ___ \| |_) | |_) | | | (_| | \__ \ | | | | (_| |
# /_/   \_\ .__/| .__/|_|  \__,_|_|___/_|_| |_|\__, |
#         |_|   |_|                            |___/

class Appraising(models.Model):
    class Meta:
        verbose_name = _('Appraising')
        verbose_name_plural = _('Appraisings')

    def __str__(self):
        return str(self.amember) + _(' appraise ') + str(self.acontent)

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    amember = models.ForeignKey(
        to='ASharingGroupMember',
        on_delete=models.CASCADE,
        verbose_name=_('Appraisings from'))
    acontent = models.ForeignKey(
        to='ASharingContent', on_delete=models.CASCADE,
        verbose_name=_('Content'))
    appraising_point = {'min': 0, 'max': 10}
    point = models.SmallIntegerField(
        default=appraising_point['min'],
        validators=[
            MinValueValidator(appraising_point['min']),
            MaxValueValidator(appraising_point['max'])])
    DOA = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Date of Appraising'))
    comment = models.CharField(
        max_length=64, verbose_name=_('Comment'))


class ASharingContent(models.Model):
    class Meta:
        verbose_name = _('Appraising content')
        verbose_name_plural = _('Appraising contents')

    def __str__(self):
        return self.title

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True)

    cfrom = models.ForeignKey(
        to=Funuser, on_delete=models.CASCADE, verbose_name=_('Content from'))

    title = models.CharField(max_length=64, blank=False,
                             verbose_name=_('Title'))

    content = RichTextUploadingField(
        max_length=2048,
        verbose_name=_('Content'))

    DOC = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Date of appraising content creating'))

    DOU = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Date of appraising content updating'))
    agroup = models.ForeignKey(
        to='ASharingGroup', on_delete=models.CASCADE, null=False, blank=False,
        verbose_name=_('Classification'))
    classification = models.ForeignKey(
        to=Classification, on_delete=models.SET_NULL, null=True,
        verbose_name=_('Classification'))

    comment = models.TextField(max_length=128, verbose_name=_(
        'Eduhub homepage sticker comment'))

    is_legal = models.BooleanField(
        default=True, verbose_name=_('Is content legal'))


def asharinggroup_upload_to(instance, filename):
    return '{0}/{1}'.format(instance.founder.username, filename)


class ASharingGroup(models.Model):
    class Meta:
        verbose_name = _('ASharingGroup')
        verbose_name_plural = _('ASharingGroups')

    def __str__(self):
        return self.name
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(
        max_length=64, blank=False, verbose_name=_('Name'))
    subtitle = models.CharField(
        max_length=64, blank=False, verbose_name=_('Subtitle'))
    cover = models.ImageField(
        upload_to=asharinggroup_upload_to,
        blank=True,

fun/funhome/models.py
import uuid

from ckeditor.fields import RichTextField
from ckeditor_uploader import fields
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from funfile.storage import upload_to
from funuser.models import Funuser

# Put the readability of your code first
# Create your models here.

homesticker_name = 'homesticker'
funhomesticker_name = 'funhomesticker'
appreciation_name = 'appreciation'


class Homesticker(models.Model):

    class Meta:
        verbose_name = _(
            'Home sticker(deprecation)')
        verbose_name_plural = _(
            'Home sticker(deprecation)')

    def __str__(self):
        return self.title

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4,
        editable=False,)

    title = models.CharField(
        max_length=32, verbose_name=_('Sticker title'))

    subtitle = models.TextField(
        max_length=64, verbose_name=_('Sticker subtitle'))

    cover = models.ImageField(
        upload_to=upload_to, verbose_name=_('Sticker cover'))

    promulgator = models.ForeignKey(
        to=Funuser, on_delete=models.CASCADE,
        verbose_name=_('Sticker promulgator'))

    content_file = models.FileField(
        upload_to=upload_to, verbose_name=_('Sticker content file'))

    promulgating_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Sticker promulgating date'))

    comment = models.TextField(
        max_length=128,
        verbose_name=_('Sticker comment'))

    is_hidden = models.BooleanField(
        default=False,
        verbose_name=_('Hidden') + " ?")


class Funhomesticker(models.Model):

    class Meta:
        verbose_name = _('Home sticker') + f'({_("NEW")})'
        verbose_name_plural = _('Home stickers') + f'({_("NEW")})'

    def __str__(self):
        return self.title

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,)

    title = models.CharField(
        max_length=32,
        verbose_name=_('Sticker title'))

    subtitle = models.TextField(
        max_length=64,
        verbose_name=_('Sticker subtitle'))

    cover = models.ImageField(
        upload_to=upload_to,
        verbose_name=_('Sticker cover'))

    promulgator = models.ForeignKey(
        to=Funuser,
        on_delete=models.CASCADE,
        verbose_name=_('Sticker promulgator'))

    content = fields.RichTextUploadingField()

    promulgating_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Sticker promulgating date'))

    comment = models.TextField(
        max_length=128, verbose_name=_('Sticker comment'))

    is_hidden = models.BooleanField(
        default=False, verbose_name=_('Hidden') + " ?")


class Appreciation(models.Model):

    class Meta:
        verbose_name = _('Appreciation')
        verbose_name_plural = _('Appreciation')

    def __str__(self):
        return self.brief_comment

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    invitee = models.CharField(
        max_length=8,
        verbose_name=_('invitee')
    )

    invitee_title = models.CharField(
        max_length=8,
        verbose_name=_('invitee title')
    )

    brief_comment = models.CharField(
        max_length=16,
        verbose_name=_('brief comment')
    )

    illustration = models.ImageField(
        upload_to=upload_to,
        verbose_name=_('illustration')
    )

    home_comment = models.TextField(
        max_length=128,
        verbose_name=_('home comment'),
    )

    content = fields.RichTextUploadingField(
        max_length=4096,
        verbose_name=_('appreciation content')
    )

    submitter = models.ForeignKey(
        to=Funuser,
        on_delete=models.CASCADE,
        verbose_name=_('Submitter')
    )

    submitting_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Submitting date')
    )

fun/funhome/templates/funhome/_base.html
{% comment %}
Some files and folders start with 'f' and I do this simply because the project 
was boring at the beginning and I was worried about the duplication of the 
naming and you don't need to do it like I did.
{% endcomment %}


{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        
        <meta name="viewport" 
            content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
            
        <title>{% block title %}x-dove{% endblock title %}</title>
        
        {% include 'funhome/_css.html' %}
        
        {% comment %}
            optional css
        {% endcomment %}
        {% block optionalcss %}{% endblock optionalcss %}

    </head>

    <body >
        <header>
            {% include 'funhome/_navbar.html' %}
            {% block subnavbar %}{% endblock subnavbar %}
        </header>

        <div class="container body-content">
            {% block content %}
            {% endblock content %}
        </div>
        
        {% include 'funhome/_footer.html' %}
        
        {% include 'funhome/_js.html' %}
        
        {% comment %}
            With jQuery, Bootsreap and so on . . .
        {% endcomment %}
        {% block optionaljs %}{% endblock optionaljs %}
        
    </body>
        
</html>

fun/funhome/templates/funhome/_common_pagination.html
{% load i18n %}
{% load l10n %}


{% if page_obj %}
    <div class="pagination justify-content-center  align-items-center mt-5" 
        style="font-size: large;">
        <span class="step-links">
            {% if page_obj.has_previous %}

                {% if page_obj.number|add:'-1' != 1 %}
                    <a href="?page=1" class="btn btn-primary btn-sm">
                        &laquo; {% trans 'first page' %}
                    </a>
                {% endif %} 

                <a href="?page={{ page_obj.previous_page_number }}"  
                    class="btn btn-primary btn-sm">
                    {% trans 'previous page' %}
                </a>

            {% endif %}

            <span class="current">
                {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
                {% trans 'Page' %} 
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"  
                    class="btn btn-primary btn-sm">{% trans 'next page' %}</a>

        {% if page_obj.number|add:'1' != page_obj.paginator.num_pages %}
                    <a href="?page={{ page_obj.paginator.num_pages }}"  
                        class="btn btn-primary btn-sm">
                        {% trans 'last page' %} &raquo;
                    </a>
        {% endif %}
            
            {% endif %}

        </span>
    </div>
{% endif %}

fun/funhome/templates/funhome/_css.html
{% load static %} 
{% load funhome_tags %}

{# Try to be as simple and beautiful as possible here #}
<style>
    html{
        overflow-y:scroll;
        {% get_site_gray as site_gray %}
        {% if site_gray %}
            filter: grayscale(100%);
        {% endif %}
    }
</style>

<link rel="stylesheet" href="{% static 'fun.css' %}"/>
<link rel="stylesheet" href="{% static 'keyframes.css' %}"/>

<link rel="stylesheet" href="{% get_current_theme_url %}"/>

fun/funhome/templates/funhome/_footer.html
{% load i18n %}
{% load l10n %}
{% load account %}
{% load funhome_tags %}
{% load tz %}

<footer class="border-top footer text-muted">
    <div class="container ">
        <div class="row align-items-center justify-content-center">

            <div class="col col-auto">
                &copy; {% now "Y" %} 
                {# a bug >> site name coudn`t get here #}
                - <a href="/"> 
                    {% blocktrans %}
                        x-dove
                    {% endblocktrans %} 
                </a>
            </div>
            
            <div class="col col-auto">
                <a href="{% url 'legal_information' %}">
                    {% trans 'Legal information' %}
                </a>
            </div>
            <div class="col col-auto">
                <a href="{% url 'data_privacy' %}">
                    {% trans ' Data privacy' %}
                </a>
            </div>
            <div class="col col-auto">
                <a href="#">{% trans 'Developer' %}</a>
            </div>
            <div class="col col-auto float-right">
                {% include 'funhome/_footer_language.html' %}
            </div>
            <div class="col col-auto float-right">
                {% include 'funhome/_footer_theme.html' %}
            </div>
            <div class="col col-auto">
                <a href="https://github.com/larryw3i/fun">
                    {% trans 'this site' %}
                </a>
            </div>

            {% get_beian_text as beian_text %}
            {% if beian_text %}
                <div class="col col-12 text-center beian_text">
                    <a href="{% get_beian_url %}" class="small">
                        {{ beian_text }}
                    </a>
                </div>
            {% endif %}
        </div>

    </div>
</footer>

fun/funhome/templates/funhome/_footer_language.html
{% load i18n %}
{% load l10n %}
 
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}


<form action="{% url 'set_language' %}" method="post" id="language_form" 
    hidden>
    {% csrf_token %}
    <input name="next" value="{{ request.path }}"/>
    <input name="language" /> 
</form>

<div class="btn-group dropup">
    <button type="button" class="btn  dropdown-toggle " id="languageDropdown" 
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {{ LANGUAGE_CODE|language_name_local }}
    </button>
    <div class="dropdown-menu  language-dropdown-menu"  
        aria-labelledby='languageDropdown'>

        <span class="dropdown-item-text btn-sm" >{% trans 'language' %}</span>
        <div class="dropdown-divider small"></div> 
        
        {% for language in languages %} 
            <a class="language-dropdown-item dropdown-item btn-link btn-sm" 
                data-language="{{ language.code }}" >
                {{ language.name_local }}
            </a>
            
        {% endfor %} 
    </div>
</div>

fun/funhome/templates/funhome/_js.html
{% load static %}

<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}" ></script>

<script
    src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}">
</script>

<script 
    src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}">
</script>

<script src="{% static 'node_modules/js-cookie/src/js.cookie.js' %}" ></script>

<script src="{% url 'javascript-catalog' %}"></script>

<script src="{% static 'fun.js' %}"></script>

<script src="{% static 'funstatic.js' %}"></script>

fun/funhome/templates/funhome/_navbar.html
{% load i18n %}
{% load l10n %}
{% load static %}
{% load account %}
{% load funhome_tags %}
{% load funuser_tags %}

<nav class="navbar navbar-inverse navbar-fixed-top navbar-expand-sm ">
    <div class="container">
        <a class="navbar-brand" href="/">x-dove</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" 
            data-target="#funNavbarContent" aria-controls="funNavbarContent" 
            aria-expanded="false" aria-label="Toggle navigation">
            <span >=</span>
        </button>
        
        <div class="collapse navbar-collapse" id="funNavbarContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">
                        {% trans 'Home' %} 
                        <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'eduhub:label_list' %}">
                        {% trans 'Eduhub' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{% trans 'Developers' %}</a>
                </li>
                {% comment %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"  id="messageDropdown" 
                        role="button" data-toggle="dropdown" 
                        aria-haspopup="true" aria-expanded="false">
                        {% trans 'Message' %}
                    </a>
                    <div class="dropdown-menu" 
                        aria-labelledby="messageDropdown">
                        {% for message in messages %}
                            <a class="dropdown-item" href="#">{{message}}</a>
                        {% endfor %}
                    </div>
                </li>
                {% endcomment %}
            </ul>

            {% get_allow_registration as allow_registration %}
            
            <ul class="form-inline navbar-nav my-2 my-lg-0"> 
            
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"  
                            id="user_dropdown" 
                            role="button" data-toggle="dropdown" 
                            aria-haspopup="true" aria-expanded="false">
                            {{ request.user }}
                        </a>
                        <div class="dropdown-menu" 
                            aria-labelledby="user_dropdown">
                            <a class="dropdown-item" 
                                href="{% url 'funuser:funuser_update' %}">
                                &#128458;{% trans "Information" %}
                            </a>
                            <a class="dropdown-item" 
                                href="{% url 'fnotification:list' %}">
                                &#128276;{% trans "Notification" %}
                            </a>
                            <a class="dropdown-item" 
                                href="{% url 'funblog:list' %}">
                                &#128221;{% trans "Blog" %}
                            </a>
                            <a class="dropdown-item" 
                                href="/accounts/password/reset/">
                                &#128584;{% trans "Password" %}
                            </a>
                            <a class="dropdown-item" 
                                href="{% url 'account_logout' %}">
                                &#8627;{% trans 'Log Out' %}
                            </a>
                        </div>
                    </li>

                {% else %}                
                    <li class="nav-item">
                        <a class="p-2 text-dark" 
                            href="{% url 'account_login' %}">
                            {% trans 'Log In' %}
                        </a>
                    <li/>
                    {% if allow_registration %}
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" 
                                href="{% url 'account_signup' %}">
                                {% trans 'Sign Up' %}
                            </a>
                        <li/>
                    {% endif %}
                {% endif %}
            
            </ul>

        </div>
    </div> 
</nav>

fun/funhome/templates/funhome/data_privacy.html
{% extends 'funhome/_base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load i18n %}
{% load l10n %}
{% load tz %}

{% block title %}  {% endblock title %}

{% block optionalcss %}

{% endblock optionalcss %}

{% block content %} 
    
{% endblock content%}

{% block optionaljs %}

{% endblock optionaljs %}
 

fun/funhome/templates/funhome/funhomesticker_list.html
{% extends 'funhome/_base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load i18n %}
{% load l10n %}
{% load tz %}


{% block title %}
    {% trans 'Sticker list'  %}
{% endblock title %}

{% block content %} 

    <h5 class="text-center font-weight-bold">{% trans 'Sticker list' %}</h5>
    <hr/>
    <a href="{% url 'homesticker_list' %}" 
        class="btn btn-sm btn-outline-info float-right">{% trans 'Older' %}</a>
    <div class="row">

        {% for funhomesticker in funhomestickers %}

            <div class="col  col-sm-6 col-md-4 col-lg-3 col-xl-3 col-12 mt-2">
                <div class="card bg-transparent text-white click-to-url 
                    homesticker-list-card" 
                    data-url=
                    "{% url 'funhomesticker_detail' pk=funhomesticker.id %}">

                    <img src="/media/{{ funhomesticker.cover.name }}" 
                        class="card-img" alt="cover"/>

                    <div class="card-img-overlay">
                        <div class="homesticker-list-card-text">

                            <p class="card-title text-center">
                                {{ funhomesticker.title }}
                            </p>

                            <p class=
                                "card-subtitle text-center d-none d-md-block">
                                {{ funhomesticker.subtitle }}
                            </p>

                            <p class="card-text text-right">
                                {{ funhomesticker.promulgating_date }}
                            </p>
                            
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>


    {% include 'funhome/_common_pagination.html' %}

{% endblock %}

fun/funhome/templates/funhome/home.html
{% extends 'funhome/_base.html' %}

{% load i18n %}
{% load l10n %}
{% load tz %}
{% load funhome_tags %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
    {% if user.is_authenticated %}
        {# workspace #}
        Hello!
        {% comment %}
        <script> location.href = `{% url 'eduhub:label_list' %}`; </script>
        {% endcomment %}
    {% else %}
        {# welcome #}
        {% include 'funhome/home_funhomesticker.html' %}
        <hr/>
        {% include 'funhome/home_appreciation.html' %}
    {% endif %}

    {% get_allow_registration as allow_registration %}
    {% if allow_registration %}
        <hr/>
        {% include 'funhome/home_join_us.html' %}
    {% endif %}

{% endblock content %}